// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolsticeCodeChallengeWebAPI.Models;

namespace SolsticeCodeChallengeWebAPI.Migrations
{
    [DbContext(typeof(ContactDbContext))]
    [Migration("20190323185832_Migration3")]
    partial class Migration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SolsticeCodeChallengeWebAPI.Models.Contact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("ProfileImageURL");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("SolsticeCodeChallengeWebAPI.Models.Contact", b =>
                {
                    b.OwnsOne("SolsticeCodeChallengeWebAPI.Models.Address", "Address", b1 =>
                        {
                            b1.Property<long>("id")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("AddressLine1");

                            b1.Property<string>("AddressLine2");

                            b1.Property<long>("AddresssContactForeignKey");

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("State")
                                .IsRequired();

                            b1.HasKey("id");

                            b1.ToTable("Contacts");

                            b1.HasOne("SolsticeCodeChallengeWebAPI.Models.Contact", "Contact")
                                .WithOne("Address")
                                .HasForeignKey("SolsticeCodeChallengeWebAPI.Models.Address", "id")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("SolsticeCodeChallengeWebAPI.Models.ContactPhone", "ContactPhone", b1 =>
                        {
                            b1.Property<long>("ContactId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<long>("ContactPhoneid");

                            b1.Property<long>("ContactPhonesContactForeignKey");

                            b1.Property<string>("PersonalPhone")
                                .IsRequired();

                            b1.Property<string>("WorkPhone");

                            b1.HasKey("ContactId");

                            b1.ToTable("Contacts");

                            b1.HasOne("SolsticeCodeChallengeWebAPI.Models.Contact", "Contact")
                                .WithOne("ContactPhone")
                                .HasForeignKey("SolsticeCodeChallengeWebAPI.Models.ContactPhone", "ContactId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
